### ISSUE TITLE
repository refactoring for a clean new start

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-sys-setup#22]
## Motivation

Redesign of the repo in order to be up to date with the progress of the Pyronear project and to facilitate contribution by new contributors

## Pitch 
Due to a lack of time to refine and test many elements of this repo last summer, the repo is not up to date with the evolution of the project. 

This refacto aims to update the repo by proposing a new and clearer structure while keeping the old elements for the moment.

- The general idea is to have playbooks related to each type of installation (according to each deployment situation encountered, for the case of a system in a garden with a single central raspberry taking pictures, etc etc)
- Roles will thus serve as installation toolbox from which to build the different playbooks
- At least for testing purpose, the folder *playbooks/role_playbooks* (name can be discussed), will contain a playbook for each role (and for an appropriate host)
- The documentation needs to be reviewed in order to understand the philosophy of the repo, but more importantly, to be able to do the complete set up of a system :)
- we keep the possibility to pass some roles/playbooks as relics to be cleaned/deleted later

Once this directory is in order, it will be time to create a nice first playbook about the installation made in Ardeche :)

## Tasks

- [ ] rewrite documentation
- [ ] migrate mono step playbooks to roles
     - [x] #23
     - [ ]  add_jobs_crontab
     - [ ] common_playbook
     - [ ] install_ansible_rpi_main
     - [ ] install_local_api_dependencies
     - [ ] install_open_vpn_client
     - [ ] install_pyroengine
     - [ ] install_vision_dependancies
     - [ ] set_up_node_exporter_rpi
     - [ ] setup_reverse_proxy_rpi_main
     - [ ] stop_service_playbook
- [ ] test and migrate mono stepp palybooks to playbooks/role_playbooks

Happy to discuss it !
